version: "3.0"
services:
  postgresdb:
   image: postgres:14.3
   container_name: postgresdb_aluno_jdbc
   environment:
     - TZ=America/Sao_Paulo
     - POSTGRES_USER=gabriel
     - POSTGRES_PASSWORD=gabriel
     - POSTGRES_DB=alunojdbc
   ports:
     - 5000:5432
   restart: always
   volumes:
     - ./vol-db:/var/lib/postgresql/data
   networks:
     - backend
networks:
  backend:
    driver: bridge